language: python
sudo: false
python:
  - "3.5"
  - "3.6"
  - "nightly"
matrix:
  allow_failures:
    - python: "nightly"
  include:
    - { python: "3.7", dist: xenial, sudo: true }
install:
  - pip install django injector pytest pytest-cov
script:
  - pytest
